### PR TITLE
Followed lecture slides to install navbar and flash alerts, and generate the views for devise

### PR DESCRIPTION
**Pull request by zyehia**

### CODE REVIEW

**Comment by zyehia** [comment]
In this commit, I 

* Followed lecture slides to install navbar and flash alerts
* Ran the command `rails g devise:views` to make the user authentication views generated by `devise` look nicer (shown in lecture slides)

The reason I closed it and then re-opened it was because I thought that, for simplicities sake, I could delete the pull request and then just re-upload it after doing the `rails g devise:views`, but that didn't work :P

**Review by gcarter89 — APPROVED** [review]
Had a look. The code looks good. Will need to see how it works when deployed in heroku.

**Review by gcarter89 — APPROVED** [review]
Renders of partials look good. Good start on the view.

**Review by gcarter89 — APPROVED** [review]

**Review by gcarter89 — APPROVED** [review]
Repeating myself, but this is good.

**Pull request merged**
